export const primaryColor = 'hsla(209, 50%, 45%, 1)'
export const rasterSize = 12
export const nodeHorizontalPadding = rasterSize
export const nodeVerticalPadding = rasterSize/4
export const nodeBorderRadius = rasterSize/2
export const nodeSpacing = rasterSize
export const nodeBackgroundColor = '#ffffcc'
export const nodeBorderColor = '#000000'
export const externalNodeBorderColor = '#777777'
export const externalNodeBackgroundColor = '#eeeeee'
export const edgeColor = '#00000077'
export const edgeWidth = 2
export const externalEdgeColor = edgeColor
export const externalEdgeWidth = 1
export const groupSpacing = 2*rasterSize
